---
application_domain: demo.com
application_name: webapp.go
application_binary: webapp
firewall_disable_firewalld: true
firewall_disable_ufw: true
firewall_allowed_tcp_ports:
  - 22
  - 80
nginx_remove_default_vhost: true
nginx_vhost_template: demo_vhost.j2
nginx_vhosts:
  - listen: 80 default_server
    server_name: "{{ application_domain }}"
    access_log: "/var/log/nginx/{{ application_domain }}-access.log"
    error_log: "/var/log/nginx/{{ application_domain }}-error.log"
    state: present
    template: "{{ nginx_vhost_template }}"
    extra_parameters: |
      location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8080;
      }
go_tarball: "go1.9.2.linux-amd64.tar.gz"
go_version_target: "go version go1.9.2 linux/amd64"
set_go_path: true
supervisord_apps:
  - {
      name: "webapp",
      command: "/var/www/demo.com/webapp",
      user: "root",
      directory: "/var/www/demo.com",
      stdout_logfile: "/var/log/supervisor/webapp.log",
      stderr_logfile: "/var/log/supervisor/webapp-error.log"
    }
